# @package _global_
defaults:
  - /pipeline: aan
  - /model: transformer

model:
  dropout: 0.
  n_layers: 6
  d_model: 256
  prenorm: true
  norm: batch

decoder:
  mode: pool

loader:
  batch_size: 6

optimizer:
  lr: 0.002
  weight_decay: 0.

scheduler:
  patience: 20

trainer:
  max_epochs: 20

train:
  seed: 1112
